version: '3.8'

services:
  mongodb:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=trivia

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/trivia
      - PORT=3001
    restart: always
    # Wait for MongoDB to be ready before starting the application
    command: >
      sh -c "
        echo 'Waiting for MongoDB to be ready...' &&
        while ! nc -z mongodb 27017; do
          sleep 1
        done &&
        echo 'MongoDB is ready!' &&
        npm run seed &&
        npm start
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - backend
    restart: always

volumes:
  mongo-data: